Ходьков Ф
alinkov/test-practice pull request #7
Opened 2019-03-25 20:39 UTC by fkhodkov

2019-03-29 08:21 UTC, alinkov requested changes
В общем могу зачесть с недочетами.
Но стоит понимать самое главное, что тесты должны тестировать какую-либо логику, сериализацию и т.д.
Тесты для конструкторов и геттеров и сеттеров писать не нужно)

2019-03-29 08:21 UTC, alinkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/service/TodoServiceTest.java
> +      fail("Should not throw this");
не совсем понимаю зачем?

2019-03-29 08:21 UTC, alinkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/exceptions/TodoNotFoundExceptionTest.java
> +    throw new TodoNotFoundException();
ахах)
Тесты ради тестов.
Это как раз то, для чего не нужно писать тесты.
Если у тебя в коде используется это исключение, то оно все равно будет покрыто.
Просто в нем нет никакой логики. Если нет логики, то и тестировать не нужно.

2019-03-29 08:21 UTC, alinkov commented on src/main/java/ru/hh/school/fkhodkov/todomvc/dao/TodoDAO.java
> +  public int count();
в интерфейсах паблик писать не обязательно

2019-03-29 08:21 UTC, alinkov commented on src/main/java/ru/hh/school/fkhodkov/todomvc/dao/TodoNoDBDAO.java
> +public class TodoNoDBDAO implements TodoDAO {
старайся не писать так много больших символов подряд. 
В гугл чекстайл по-моему нельзя больше 2

2019-03-29 08:21 UTC, alinkov commented on src/main/java/ru/hh/school/fkhodkov/todomvc/dao/TodoNoDBDAOFactory.java
> +  public static final TodoDAO todoDAO = new TodoNoDBDAO();
зачем public?

2019-03-29 08:21 UTC, alinkov commented on src/main/java/ru/hh/school/fkhodkov/todomvc/dto/TodoCollectionDTO.java
> +    this.items = new ArrayList<TodoItemDTO>();
если так, то лучше создавать сразу с размера items.
Ну а вообще лучше было бы так
```java
this.items = items.stream()
.map(TodoItemDTO::new)
.collect(Collectors.toList());
```

2019-03-29 08:21 UTC, alinkov commented on src/main/java/ru/hh/school/fkhodkov/todomvc/model/TodoItem.java
> +    return todoItem.status == TodoStatus.ACTIVE;
возможный NPE)

2019-03-29 08:21 UTC, alinkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/dto/TodoItemDTOTest.java
> +public class TodoItemDTOTest {
для дто тесты обычно не пишутся.
Потому что в дто не должно быть никакой логики

2019-03-29 10:34 UTC, fkhodkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/exceptions/TodoNotFoundExceptionTest.java
> +    throw new TodoNotFoundException();
Ха, я сделал все возможные варианты конструкторов (без параметров, с message, с cause, с message и cause), а реально использую только один из них. Поэтому jacoco ругался на недостаточное покрытие. Уберу тогда ненужные конструкторы совсем.

2019-03-29 12:28 UTC, fkhodkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/service/TodoServiceTest.java
> +      fail("Should not throw this");
Что именно зачем?

2019-03-29 14:45 UTC, alinkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/service/TodoServiceTest.java
> +      fail("Should not throw this");
Зачем этот блок catch?
Что-то поменяется, если ты его уберешь?

2019-03-29 14:45 UTC, alinkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/exceptions/TodoNotFoundExceptionTest.java
> +    throw new TodoNotFoundException();
Да. В таком случае лучше их не создавать)

2019-03-29 15:20 UTC, fkhodkov commented on src/test/java/ru/hh/school/fkhodkov/todomvc/service/TodoServiceTest.java
> +      fail("Should not throw this");
Да, убрал

2019-03-31 19:58 UTC, alinkov approved these changes

2019-03-31 19:58 UTC, alinkov commented
Засчитано

2019-03-31 19:58 UTC, closed without merging